"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭](bold mono07)\
$shell\
$username\
$directory\
$git_branch$git_status\
$package$mise\
[$nodejs$bun$lua$python$c$cpp$rust$zig$golang](fg:mono11)\
$fill\
$cmd_duration\
$os\
$time\
$line_break\
[╰─](bold mono07)\
$character"""

palette = 'noidilin'

[palettes.noidilin]
mono25 = '#eaeaea'
mono24 = '#dcdcdc'
mono23 = '#cccccc'
mono22 = '#c0c0c0'
mono21 = '#b3b3b3' # text
mono20 = '#aaaaaa'
mono19 = '#9d9d9d' # subtext1
mono18 = '#8e8e8e'
mono17 = '#878787' # subtext0
mono16 = '#7f7f7f'
mono15 = '#707070' # overlay2
mono14 = '#686868'
mono13 = '#5d5d5d' # overlay1
mono12 = '#555555'
mono11 = '#4e4e4e' # overlay0
mono10 = '#474747'
mono09 = '#414141' # surface2
mono08 = '#3a3a3a'
mono07 = '#353535' # surface1
mono06 = '#303030'
mono05 = '#2a2a2a' # surface0
mono04 = '#242424'
mono03 = '#1e1e1e' # base
mono02 = '#191919' # mantle
mono01 = '#151515' # crust
mono00 = '#101010'
# accent
acc08 = '#faf5eb'
acc07 = '#dad5c8'
acc06 = '#c0baad'
acc05 = '#b3ad9f'
acc04 = '#a69f91'
acc03 = '#9a9487'
acc02 = '#8e897d'
acc01 = '#7f7b70'
acc00 = '#706c62'
accDim08 = '#f7f4ed'
accDim07 = '#d6d3cc'
accDim06 = '#bdbab2'
accDim05 = '#b4b0a7'
accDim04 = '#a19d97'
accDim03 = '#97948c'
accDim02 = '#8e8b85'
accDim01 = '#7b7974'
accDim00 = '#6c6a65'
# color
red01 = '#cc9393'
red00 = '#b07878'
green01 = '#9bb09b'
green00 = '#778777'
yellow01 = '#ebd6b7'
yellow00 = '#d6caab'
blue01 = '#9db2cf'
blue00 = '#7d96ad'
magenta01 = '#9f9fbd'
magenta00 = '#797994'
cyan01 = '#92b3b3'
cyan00 = '#769494'
orange01 = '#dcb5a5'
orange00 = '#c8a492'

[fill]
symbol = ' '

[character]
success_symbol = '[](bold fg:mono21)'
error_symbol = '[](bold fg:red00)'

# left
[shell]
disabled = false
format = '[  $indicator ]($style)'
style = 'fg:mono21'

[username]
format = '[ $user ]($style)'
style_user = 'fg:mono19 bold'
style_root = 'fg:acc08 bold'

[directory]
format = '[ $path ]($style)'
truncation_length = 3
truncation_symbol = '…/'
style = 'fg:mono17'

# [directory.substitutions]
# "learning" = ' '
# "dev" = '󰲋 '
# "downloads" = ' '

[git_branch]
symbol = ''
format = '[[ $symbol $branch ](fg:mono15)]($style)'
style = 'bg:mono09'

[git_status]
format = '[[($all_status$ahead_behind )](fg:mono15)]($style)'
style = 'bg:mono09'

[package]
format = ' is [$symbol$version]($style)'
symbol = ' '
style = 'mono09 bold'

[mise]
disabled = false
format = ' on [$symbol$health]($style)'
style = 'mono09 bold'

# right
[cmd_duration]
disabled = false
min_time = 500
show_milliseconds = true
format = '[ [$duration](fg:mono13)]($style)'
style = 'fg:mono09 bold'

[os]
disabled = false
format = '[ $symbol]($style)'
style = 'fg:mono11'

[os.symbols]
Windows = ' win'
Macos = '󰀵 mac'
Arch = '󰣇 arch'

[time]
disabled = false
format = '[ [$time](fg:mono09)]($style)'
time_format = '%R'
style = 'fg:mono07 bold'

# lang
[nodejs]
symbol = ''
format = ' $symbol( $version)'

[bun]
symbol = ''
format = ' $symbol( $version)'

[lua]
symbol = ''
format = ' $symbol( $version)'

[swift]
symbol = ''
format = ' $symbol( $version)'

[c]
symbol = ''
format = ' $symbol( $version)'

[cpp]
symbol = ''
format = ' $symbol( $version)'

[rust]
symbol = ''
format = ' $symbol( $version)'

[zig]
symbol = ''
format = ' $symbol( $version)'

[golang]
symbol = ''
format = ' $symbol( $version)'

[python]
symbol = ''
format = ' $symbol( $version)'

[docker_context]
symbol = ''
format = '[ $symbol( $context) ](fg:acc07 bg:mono08)'
